const data = {
  products: [
    {
      name: "Nike shirt",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/image1.jpg",
      price: 120,
      rating: 3.5,
      numberinStock: 10,
      brand: "Nike",
      rating: 4.5,
      numberofReviews: 10,
      description: "high quality",
    },
    {
      name: "Nike pant",
      slug: "nike-pant",
      category: "Pants",
      image: "/images/image2.jpg",
      price: 100,
      rating: 5,
      numberinStock: 5,
      brand: "Nike",
      rating: 4.5,
      numberofReviews: 5,
      description: "high quality",
    },

    {
      name: "Adidas shirt",
      slug: "adidas-shirt",
      category: "Shirts",
      image: "/images/image3.jpg",
      price: 120,
      rating: 1.5,
      numberinStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numberofReviews: 10,
      description: "high quality",
    },

    {
      name: "Nike shirt",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/image1.jpg",
      price: 90,
      rating: 3.5,
      numberinStock: 10,
      brand: "Nike",
      rating: 3.5,
      numberofReviews: 5,
      description: "high quality",
    },
  ],
};

export default data;
